data_root: /Users/gazizullinniyaz/Downloads/MOT17/train
sequences:
- MOT17-02-FRCNN
- MOT17-04-FRCNN
detector:
  model: /Users/gazizullinniyaz/VSCode/MOT/tmp/yolo11n.pt
  conf: 0.25
  iou: 0.7
  classes:
  - 0
  device: cpu
resize:
  imgsz: 1280
  mode: letterbox_to_1280
tracker:
  tracker_type: botsort
  track_high_thresh: 0.25
  track_low_thresh: 0.1
  new_track_thresh: 0.25
  track_buffer: 30
  match_thresh: 0.8
  fuse_score: true
  gmc_method: sparseOptFlow
  proximity_thresh: 0.5
  appearance_thresh: 0.8
  with_reid: false
  model: auto
