
data: ./sportsmot_publish/dataset/train
sequences:
  - v_-6Os86HzwCs_c001
  - v_1LwtoLPw2TU_c016
  - v_HdiyOtliFiw_c003


outdir: experiments/experiment_runs/gmc/sportsmot_gmc_test
device: "cpu"

model: ./models/detector/yolo11n.pt
conf: 0.25
iou: 0.7
imgsz: 1280
classes: [0]

tracker_config: ./configs/botsort_baseline.yaml

visualization:
  enabled: true
  fps: 30

gmc: raft

raft_gmc:
  model: small
  device: cpu
  mixed_precision: false
  scale: 2
  sample_step: 8
  ransac_reproj_threshold: 3.0
