data: /path/to/MOT17/train
sequences:
  - MOT17-02-FRCNN
  - MOT17-04-FRCNN
outdir: baseline_runs/mot17_botsort
device: "0"

# Detector
model: /Users/gazizullinniyaz/VSCode/MOT/tmp/yolo11n.pt
conf: 0.25
iou: 0.7
imgsz: 1280
classes: [0]

# Tracker
tracker_config: /Users/gazizullinniyaz/VSCode/MOT/configs/botsort_baseline.yaml

visualization:
  enabled: false
  fps: 30
  # max_frames: 300
